### ISSUE TITLE
[feature] Ability to group items by priority or other note fields

### ISSUE THREAD

**Issue by alexeystrakh** [d-koppenhagen/vscode-code-review#21]
# 🧩 Feature

## Description

One the priority is set for every note, I want to be able to see them grouped by that priority in the final report.

**Comment by d-koppenhagen** [comment]
Okay, I got this. Probably this can already be reached by playing a bit arount with the handlebar template and custom operations.

The current structure the report is using is:

```ts
export interface ReviewFileExportSection {
  filename: string;
  url: string;
  lines: {
    sha: string;
    filename: string;
    url: string;
    lines: string;
    title: string;
    comment: string;
    priority: string;
    additional: string;
  }[];
}
```

So probably an additional group structure would be nice:

```ts
export interface ReviewFileGroupExportSection {
  high: ReviewFileExportSection[],
  medium: ReviewFileExportSection[],
  low: ReviewFileExportSection[],
}
```

And then a flag in the VSCode options can turn on grouping by priority. What do you think?

**Comment by alexeystrakh** [comment]
The suggested solution is what I think as well, grouping should be part of the default template (capability) which is disabled by default and then let people to decide how to group elements either during generation on even integrate controls in the default template just to chance the grouping dynamically. Any solution which allows to achieve the grouping and sorting (also important) would work.

**Comment by d-koppenhagen** [comment]
I just realize that I have to restructure it a bit.
As my first suggested behavior cannot work because currently the entries are already grouped by filename (but e.g each priority group can contain the same file with comments but different priority comments.

Probably the best would be:

- add a configuration setting to configure grouping by: 
  - `filename`
  - `priority` (second level is grouped by `filename`)
  - `category` (second level is grouped by `filename`)

**Comment by d-koppenhagen** [comment]
For sorting I would like to have another separate issue
