### ISSUE TITLE
[bug] Doesnt work. Cant generate HTML

### ISSUE THREAD

**Issue by rille111** [d-koppenhagen/vscode-code-review#32]
# 🐞 Bug report

## Description

CSV Get generated fine. Theres no HTML output at all. It worked 3 months back.

## Reproduction

Add some notes and generate HTML, use default or use custom hbs file (tried both).
If path to the default hbs is wrong, youll get the log output. When correcting the path and trying to generate, theres no error. But also, theres no file. 

## Error message

None

## 🌍 Your Environment

Windows 10 Pro. Latest version of VSCode. Minimal number of extensions, none that can interfer with this.

**Comment by d-koppenhagen** [comment]
can you please attach the generated CSV file?

**Comment by rille111** [comment]
Sure! Attaching here.
[code-review.zip](https://github.com/d-koppenhagen/vscode-code-review/files/5097253/code-review.zip)

**Comment by d-koppenhagen** [comment]
Okay, I think I got the issue.
Within a newer version I introduced the flag `code-review.reportWithCodeSelection` which is by default set to `true`. This will try to decode/encode the files content and included it in the report.
However this will crash when the file / line content cannot be found.

You can disable this feature by adding this to your `.vscode/settings.json` file:

```json
{
  // ...
  "code-review.reportWithCodeSelection": false
}
```

Please try it out. Meanwhile I will work on a fix so that it will just ignore this setting in such cases.

**Comment by d-koppenhagen** [comment]
I just published version 1.9.1 in the Marketplace. This should fix the problem even when `code-review.reportWithCodeSelection` is set to `true` as it will catch error when trying to parse a file that couldn't be found.

Please re-open the issue if you can still see this error after updating the extension.

**Comment by rille111** [comment]
Hi @d-koppenhagen ! Nice with such a fast response. Got the newest version 1.9.3. Tried the settings true and false, still nothing happens and no log out from what I can see.
Also, unable to re-open this github issue, dunno why. 

Cheers!

**Comment by rille111** [comment]
Cool, It works. Thanks!

**Comment by d-koppenhagen** [comment]
great. Your welcome. Thanks for reporting it.
