### ISSUE TITLE
[feature] Support for repository located in a subfolder

### ISSUE THREAD

**Issue by michelcaradec** [d-koppenhagen/vscode-code-review#82]
# 🧩 Feature

## Description

There can be some cases where the repository is located in a subfolder of the workspace.
In such situation, the `sha`property of the comment can't be assigned.

I suggest to add a setting `code-review.gitSubFolder` that will allow to specify a subfolder.
It will the be possible to add it in the `.vscode/settings.json` file.

**Comment by d-koppenhagen** [comment]
Great idea. Should it really be `code-review.gitSubFolder` since it's just a folder that defers from `.` isn't it?
So my suggestion would be to name it: `code-review.gitDirectory` and then using a default value of `.`. So this allows one to either define a absolute or relative path where to search for the git directory.
When it will be implemented, Windows / macOS / linux paths should be normalized / tested.
